sudo: required

language: ruby

services:
  - docker

before_install:
  - env
  - docker pull otassetti/builder-python2.7.5:centos6

script:
 - chmod 777 AnsibleBuild.sh
 - docker run -ti -v /home/travis/build/otassetti/AnsibleAsBin/:/tmp/ otassetti/builder-python2.7.5:centos6 /bin/bash -c '/tmp/AnsibleBuild.sh'

after_success:
  - echo "end"
 
