sudo: required

language: ruby

services:
  - docker

before_install:
  - ls
  - pwd
  - echo "Testing Docker Build"
  - docker pull otassetti/builder-python2.7.5:centos6
  - docker run -ti otassetti/builder-python2.7.5:centos6 /bin/bash

script:
  - ls
  - pwd
  - docker ps -a

after_success:
  - echo 
 
